version: '2'
services:
  ttiot-redis:
    image: redis:5.0
    command: redis-server --requirepass TTIot
    ports:
      - 6379:6379
    restart: always
    container_name: ttiot-redis
    hostname: ttiot-redis

  ttiot-example:
    build:
      context: ./
      dockerfile: ./ttiot-example/Dockerfile
    restart: always
    ports:
      - 8729:8729
    container_name: ttiot-example
    hostname: ttiot-example
    image: ttiot-example